version: "3.7"

services:
  kzas-db:
    image: "postgres:12.2"
    container_name: "kzas-db"
    environment:
      - POSTGRES_USER=kzas
      - POSTGRES_PASSWORD=kzas
      - POSTGRES_DB=kzas
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - default


networks:
  default:
    driver: bridge
    name: kzas